base-pojo: this commit only contains the module of common with the POJO class
juliorr/common pull request #2
Opened 2018-09-12 00:00 UTC by juliorr

Thing to be consider is this package only will contain the common module, the other code management, micro service, app, will have a separate package for each

2018-09-12 17:52 UTC, ycaceres requested changes

2018-09-12 17:52 UTC, ycaceres commented on common.iml
> +<?xml version="1.0" encoding="UTF-8"?>
gitignore

2018-09-12 18:29 UTC, wombstrat requested changes

2018-09-12 18:29 UTC, wombstrat commented on src/main/java/com/ns/task/common/Product.java
> +public class Product {
Would you find useful to add toString, hashCode and equals methods to this class?
If so, why?, and find the best practices for hashCode and Equals.

2018-09-12 18:29 UTC, wombstrat commented on pom.xml
> +      <version>4.12</version>
Put this into a properties tag.

2018-09-12 18:29 UTC, wombstrat commented on src/main/java/com/ns/task/common/Product.java
> +  private Double price;
Is it the best practice to use Double for money management?. 

Please run these lines in a test and tell me what's wrong in it. 
```
double a = 2.00;
double b = 1.10;
System.out.println(a-b);
```

2018-09-12 18:29 UTC, wombstrat commented on src/main/java/com/ns/task/common/Product.java
> +  public Integer getId() {
Is it needed the use of the Boxing?

2018-09-12 20:04 UTC, juliorr reviewed
all the changes apply

2018-09-12 20:04 UTC, juliorr commented on common.iml
> +<?xml version="1.0" encoding="UTF-8"?>
will be done

2018-09-12 20:04 UTC, juliorr commented on src/main/java/com/ns/task/common/Product.java
> +  private Double price;
I will use BigDecimal fo the money management

2018-09-12 20:04 UTC, juliorr commented on src/main/java/com/ns/task/common/Product.java
> +public class Product {
if some one need to compare two different instances of Product (with ==) in future, the recommendation is rewrite the hastCode, toString and equals methods

2018-09-12 20:04 UTC, juliorr commented on src/main/java/com/ns/task/common/Product.java
> +public class Product {
I will update my code

2018-09-12 20:04 UTC, juliorr commented on src/main/java/com/ns/task/common/Product.java
> +  public Integer getId() {
I wil leave with boxing to manage the null values (avoid the conversion of the null to 0 with int type).

2018-09-12 20:04 UTC, juliorr commented on pom.xml
> +      <version>4.12</version>
will be change

2018-09-12 22:03 UTC, wombstrat requested changes

2018-09-12 22:03 UTC, wombstrat commented on src/main/java/com/ns/task/common/Product.java
> +    for (int i = 0; i < this.getSigFields().length; ++i) {
Aren't you creating unnecessarily 2i arrays when the cycle is completed?.

2018-09-12 22:03 UTC, wombstrat commented on src/main/java/com/ns/task/common/Product.java
> +  private Object[] getSigFields() {
Nitpick question: where did you get this approach about creating and array with all attributes and using them in equals and hashCode methods?
Thx

2018-09-12 22:03 UTC, wombstrat commented on src/main/java/com/ns/task/common/Product.java
> +  private BigDecimal price;
Try this code and you'll get and error, is not enough just changing Double for BigDecimal.
```
 Product productA = new Product();
productA.setPrice(new BigDecimal(10));

Product productB = new Product();
productB.setPrice(new BigDecimal(3));

productA.getPrice().divide(productB.getPrice());
```

Also, did you get the chance to review why this doesn't work?
```
double a = 2.00;
double b = 1.10;
System.out.println(a-b);
```

It's important for any java dev to know it : P

2018-09-12 22:03 UTC, wombstrat commented on src/main/java/com/ns/task/common/Product.java
> +  @Override public String toString() {
Find a way to Improve String concatenation.

2018-09-12 22:22 UTC, juliorr commented on src/main/java/com/ns/task/common/Product.java
> +  private BigDecimal price;
- `Also, did you get the chance to review why this doesn't work?`

```
double a = 2.00;
double b = 1.10;
System.out.println(a-b);
```
for this the expected result is `0.9` but the result was `0.8999999999999`, and the reason of this is because  double in java manage this like a representation on one fraction and a exponent

- `Try this code and you'll get and error, is not enough just changing Double for BigDecimal.`

```
Product productA = new Product();
productA.setPrice(new BigDecimal(10));

Product productB = new Product();
productB.setPrice(new BigDecimal(3));

productA.getPrice().divide(productB.getPrice());
```

if we want to do that we can use the other params of the divide method. to can specify the precision and the rounding mode something like:
```
BigDecimal d = new BigDecimal(10);
BigDecimal f = new BigDecimal(3);
System.out.println(d.divide(f, 3, RoundingMode.HALF_UP));
```

2018-09-12 22:26 UTC, juliorr commented on src/main/java/com/ns/task/common/Product.java
> +    for (int i = 0; i < this.getSigFields().length; ++i) {
we are creating one array on each call of the cycle, I will fix this

2018-09-12 22:30 UTC, wombstrat commented on src/main/java/com/ns/task/common/Product.java
> +  private BigDecimal price;
Everything cool! man, My advise is if you ever start to write divide-substract-sum operations, create a "factory" class  to have this BigDecimal customization in only one place and not spread out throughout all your code.

2018-09-12 22:40 UTC, juliorr commented on src/main/java/com/ns/task/common/Product.java
> +  private Object[] getSigFields() {
I was reading http://www.javapractices.com/home/HomeAction.do, to refresh some information about the `hasCode`,` toString` and `equals` rewrite method  and on hasCode section I saw that code and I liked.

2018-09-12 22:47 UTC, juliorr commented on src/main/java/com/ns/task/common/Product.java
> +  @Override public String toString() {
will do

2018-09-12 22:50 UTC, juliorr reviewed
All the comments already done

2018-09-14 22:25 UTC, wombstrat commented on src/main/java/com/ns/task/common/Product.java
> +  private Object[] getSigFields() {
Ok np, only use method name more descriptive, the example from that source uses getSignificantFields

2018-09-14 22:31 UTC, wombstrat commented on src/main/java/com/ns/task/common/Product.java
> +    return ReflectionToStringBuilder.toString(this);
Didn't know this implementation, seems to work fine. 

👍

2018-09-17 23:10 UTC, wombstrat approved these changes

2018-09-17 23:26 UTC, motenrique approved these changes

2018-09-18 22:51 UTC, ycaceres requested changes

2018-09-18 22:51 UTC, ycaceres commented on src/main/java/com/ns/task/common/Product.java
> +    return ReflectionToStringBuilder.toString(this);
I think this is overkilling

2018-09-18 23:17 UTC, juliorr commented on src/main/java/com/ns/task/common/Product.java
> +    return ReflectionToStringBuilder.toString(this);
done

2018-09-18 23:17 UTC, juliorr reviewed
changes done

2018-09-18 23:19 UTC, ycaceres approved these changes

2018-09-18 23:19 UTC, merged